[package]
name = "newsletter-service"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "newsletter_service"

[dependencies]
actix-web = "^4.0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }